version: "3.8"
services:
  react:
    image: giorgosmarinoss/crud_react
    container_name: client
    ports:
      - "3000:3000"
    networks:
      pern-app:
    stdin_open: true
    tty: true

  server:
    image: giorgosmarinoss/crud_server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      pern-app:

  postgres:
    image: giorgosmarinoss/crud_postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DATABASE: mydb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5438:5432"
    networks:
      pern-app:
    volumes: 
      - ./pgdata:/var/lib/postgresql/data

networks:
  pern-app:
volumes:
  pgdata:
    driver: local